version: '3.7'
services:
  vk-api:
    build: ./api
    command: ./api/bin/rails s -p 3001 -b '0.0.0.0'
    volumes:
      - '.:/valkyrie-api'
    ports:
      - '3001:3001'
    depends_on:
      - db
  vk-ui:
    build: ./ui
    command: npm run dev
    volumes:
      - '.:/vk-ui'
    ports:
      - '3000:3000'
    depends_on:
      - vk-api
  db:
    image: postgres:12.1-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
