version: '3.7'
services:
  vk:
    build: .
    command: bin/rails s -p 3000 -b '0.0.0.0'
    volumes:
      - '.:/valkyrie'
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: postgres:12.1-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
